name: CONSTANT_BACKEND_CI

on:  
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "*" ]

jobs:
  CI:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.CONSTANT_MYSQL_PASSWORD }}
          MYSQL_DATABASE: constant
        ports:
          - 3306:3306
          
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create application.yml
        run: |
          echo "${{ secrets.CONSTANT_ENV }}" > ./src/main/resources/application.yml
        shell: bash

      - name: Run build with Gradle wrapper
        run: ./gradlew clean build
